### ISSUE TITLE
Bitcoin Aggregated/The School of Bitcoin/#getoffzero/Bitcoin Meetups Australia

### ISSUE THREAD

**Issue by kdnolan** [Fiach-Dubh/BITCOIN-YouTube#1]
I run a bunch of Bitcoin podcasts all under the "Bitcoin Aggregated" banner

Would I be able to upload them to "Bitcoin-Youtube" as well?

Great initiative! 

Cheers :)

**Comment by Fiach-Dubh** [comment]
I'll add you to the first round invite list under the influencers category for now. though you may be in the educator category after I review your content. I'll try to provide some general feedback within the week and go from there. Thanks for your interest in the project!

**Comment by kdnolan** [comment]
Thanks, mate! 🙂

**Comment by Fiach-Dubh** [comment]
I think we'll give you a shot. Some constructive feedback I have though. long form discussions/zoom calls that don't get to the point are not ideal for this channel. Tutorials, short explanations or coverage of significant bitcoin events and history are preferred. 

What gmail email do you want account access through?

**Comment by kdnolan** [comment]
***@***.***

I'll probs only upload the btcagg news and #getoffzero podcasts 👍🙂

**Comment by Fiach-Dubh** [comment]
apologies looks like github protects you from revealing your email address. All i see is ***@***.*** please send me a dm via my contact info listed here with your gmail address

https://github.com/Fiach-Dubh/BITCOIN-YouTube

**Comment by kdnolan** [comment]
thanks! I've cc'd admin

***@***.*** and
***@***.***

Cheers 🙂

**Comment by Fiach-Dubh** [comment]
sent an invite to your gmail with more details!

**Comment by kdnolan** [comment]
thanks :)
