### ISSUE TITLE
Soft-Fork/Covenant Dependent Layer 2 Review by Peter Todd

### ISSUE THREAD

**Issue by nerd2ninja** [Fiach-Dubh/BITCOIN-YouTube#12]
https://www.youtube.com/watch?v=qnbR8EotqQs

Audio is admittedly a little quiet not sure how to fix that.

**Comment by Fiach-Dubh** [comment]
ACK

**Comment by Fiach-Dubh** [comment]
uploaded here https://youtu.be/DHWdGiaR0F0
